version: "3"

services:
  redis:
    hostname: redis
    image: redis:alpine
    ports:
      - 6379:6379

  mail_to_task:
    env_file: .env
    image: mail_to_task__image
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mail_to_task
    ports:
      - 8191:8191
    volumes:
      - "./:/app/:rw"
    links:
      - redis
    depends_on:
      - redis

  worker:
    image: mail_to_task__image
    hostname: worker
    command: python worker.py
    env_file: .env
    volumes:
      - "./:/app/:rw"

    depends_on:
      - redis
      - mail_to_task
    links:
      - redis
      - mail_to_task

  scheduler:
    image: mail_to_task__image
    hostname: scheduler
    command: rqscheduler --url ${REDIS_URL} --db 0 -i 5
    env_file: .env
    volumes:
      - "./:/app/:rw"

    depends_on:
      - redis
      - mail_to_task
      - worker
    links:
      - redis
      - mail_to_task
      - worker
